version: '3.5'

# docker compose para desplegar servidor db postgres
services:
  postgres_server:
    container_name: postgres_server
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=mediappbd4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    restart: always

volumes:
  data-postgresql: